# cargo-make

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
#RUSTFLAGS = "-Awarnings"

[tasks.run-server]
cwd = "../server"
command = "cargo"
args = ["watch", "-x", "run", "--package", "server"]

[tasks.run-client]
cwd = "../client"
command = "trunk"
args = ["serve", "-q"]

[tasks.run-dev]
run_task.name = ["run-server", "run-client"]
run_task.parallel = true
