# cargo-make

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
#RUSTFLAGS = "-Awarnings"

[tasks.build-client]
cwd = "../client/"
command = "trunk"
args = ["build"]

[tasks.run-dev]
cwd = "../"
command = "cargo"
args = ["run"]
dependencies = ["build-client"]
